MVC_Working_With_Model_New/Models/Employee.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace MVC_Working_With_Model_New.Models
{
    public class Employee
    {
        [Key]
        [DisplayName("Employee Id ")]
        public int empid { get; set; }


        [DisplayName("Employee name")]
        //[Required]
        [DataType(DataType.Text)]
        [MaxLength(10)]
        [MinLength(1)]
        [Required(ErrorMessage = "Name is Required")]
        public string empname { get; set; }


        [Required]
        [DisplayName("Employee Department")]
        [DataType(DataType.Text)]
        public string empDept { get; set; }


        [DisplayName("Employee Email Id")]
        //[Required]
        [DataType(DataType.Text)]
        [MaxLength(10)]
        [MinLength(1)]
        [Required(ErrorMessage = "Email Id is Required")]
        public string empEmailId { get; set; }

        //[Required]
        [MaxLength(10)]
        [Required(ErrorMessage = "Phine number is Required")]
        public string empPhoneNo { get; set; }

    }
}

MVC_Working_With_Model_New/Models/ErrorViewModel.cs
using System;

namespace MVC_Working_With_Model_New.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC_Working_With_Model_New/Models/Student.cs
using System.Data.Entity;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using MVC_Working_With_Model_New.Models;
//using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.SqlServer;
using Microsoft.AspNetCore;
using Microsoft.SqlServer;
using System.Data.SqlClient;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
namespace MVC_Working_With_Model_New.Models
{
    public class Student
    {
        [Key]
        [DisplayName("Student Id")]
        public int rollno { get; set; }



        [DisplayName("Student name")]
        //[Required]
        [DataType(DataType.Text)]
        [MaxLength(10)]
        [MinLength(1)]
        [Required(ErrorMessage ="Name is Required")]
        public string name { get; set; }



        [Required]
        [DisplayName("Student Percentage")]
        public decimal percentage { get; set; }
    }
    public class ProductContext:DbContext
    {
        public DbSet<Student> Students { get; set; }
    }

}

MVC_Working_With_Model_New/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MVC_Working_With_Model_New.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: EmployeeController
        public ActionResult Index()
        {
            return View();
        }

        // GET: EmployeeController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EmployeeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EmployeeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmployeeController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: EmployeeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmployeeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: EmployeeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC_Working_With_Model_New/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC_Working_With_Model_New.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Working_With_Model_New.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC_Working_With_Model_New/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Working_With_Model_New.Models;

namespace MVC_Working_With_Model_New.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Student stud)
        {
            return View();
        }
        public IActionResult Edit()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Edit(Student stud)
        {
            return View();
        }

        public IActionResult Delete(int id)
        {
            return View();
        }
        [HttpPost]
        public IActionResult DeleteConform(int id )
        {
            return View();
        }

    }
}

MVC_Working_With_Model_New/Views/Employee/Create.cshtml
@model MVC_Working_With_Model_New.Models.Employee

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="empid" class="control-label"></label>
                <input asp-for="empid" class="form-control" />
                <span asp-validation-for="empid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="empname" class="control-label"></label>
                <input asp-for="empname" class="form-control" />
                <span asp-validation-for="empname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="empDept" class="control-label"></label>
                <input asp-for="empDept" class="form-control" />
                <span asp-validation-for="empDept" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="empEmailId" class="control-label"></label>
                <input asp-for="empEmailId" class="form-control" />
                <span asp-validation-for="empEmailId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="empPhoneNo" class="control-label"></label>
                <input asp-for="empPhoneNo" class="form-control" />
                <span asp-validation-for="empPhoneNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_Working_With_Model_New/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC_Working_With_Model_New/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Working_With_Model_New</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Working_With_Model_New</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Create">Create</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Create">Employee List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC_Working_With_Model_New - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC_Working_With_Model_New/Views/Student/Create.cshtml
@model MVC_Working_With_Model_New.Models.Student

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="rollno" class="control-label"></label>
                <input asp-for="rollno" class="form-control" />
                <span asp-validation-for="rollno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="percentage" class="control-label"></label>
                <input asp-for="percentage" class="form-control" />
                <span asp-validation-for="percentage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_Working_With_Model_New/Views/Student/Delete.cshtml
@model MVC_Working_With_Model_New.Models.Student

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.rollno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.rollno)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.percentage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.percentage)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVC_Working_With_Model_New/Views/Student/Edit.cshtml
@model MVC_Working_With_Model_New.Models.Student

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="rollno" class="control-label"></label>
                <input asp-for="rollno" class="form-control" />
                <span asp-validation-for="rollno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="percentage" class="control-label"></label>
                <input asp-for="percentage" class="form-control" />
                <span asp-validation-for="percentage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}